Add Authentication
turbocharged-potato/pypagao pull request #1
Opened 2018-05-21 17:28 UTC by indocomsoft

2018-05-21 17:33 UTC, indocomsoft commented
TODO: document in swagger

2018-05-26 13:41 UTC, sciffany requested changes

2018-05-26 13:41 UTC, sciffany commented on .rubocop.yml
> +Metrics/LineLength:
This is cheating!!!

2018-05-26 13:41 UTC, sciffany commented on .travis.yml
> +  - bundle exec rails db:setup RAILS_ENV=test
Why is this necessary?

2018-05-26 13:41 UTC, indocomsoft commented on .travis.yml
> +  - bundle exec rails db:setup RAILS_ENV=test
Cos why not?

2018-05-26 13:41 UTC, sciffany submitted a review, later dismissed

2018-05-26 13:45 UTC, closed without merging

2018-05-26 13:45 UTC, indocomsoft commented
Gonna implement inhouse JWT authentication

2018-05-26 13:45 UTC, sciffany commented
Yes!